### ISSUE TITLE
Issue running Password-Recon.py

### ISSUE THREAD

**Issue by ReDoneX0** [TeneBrae93/offensivesecurity#1]
#Python version is 3.11.8
#Kali
Traceback (most recent call last):
  File "/home/red/password-recon.py", line 49, in <module>
    main()
  File "/home/red/password-recon.py", line 34, in main
    data = json.load(file)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by TeneBrae93** [comment]
Hey @ReDoneX0 -- Thanks for this! The reason you're getting the error is because the target domain is not returning emails and/or passwords. I updated the script so it explains this rather than throwing an error!

**Comment by ReDoneX0** [comment]
Ah thank you, I didn't even think to check that.

**Comment by ReDoneX0** [comment]
I rechecked the domain in Dehashed and it shows 24 results found.

**Comment by ReDoneX0** [comment]
So I used the updated script and it pulled them down. Thank you!

**Comment by TeneBrae93** [comment]
Hmm.... if you manually look through the results, are there actual "email" and "password" combinations? The script is pulling those out, but if that specific combo doesn't exist, it will fail. 

As an alternative, you can get the raw data by doing a simple request like this:
```curl -u [username]:[apikey] -H "Accept: application/json" "https://api.dehashed.com/search?query=domain:[target_domain]&size=10000"```

And then from there, you can use cut, regex, or something else to manually pull the data you need

**Comment by TeneBrae93** [comment]
Oh perfect, just saw your note about it working with the updated script. Glad I could help!

**Comment by ReDoneX0** [comment]
> Hmm.... if you manually look through the results, are there actual "email" and "password" combinations? The script is pulling those out, but if that specific combo doesn't exist, it will fail.
> 
> As an alternative, you can get the raw data by doing a simple request like this: `curl -u [username]:[apikey] -H "Accept: application/json" "https://api.dehashed.com/search?query=domain:[target_domain]&size=10000"`
> 
> And then from there, you can use cut, regex, or something else to manually pull the data you need

Yea, once I saw the output I realized this was just grabbing the PT creds. Thanks again!!!!
